# Generated by Django 6.1 on 2026-08-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Software', 'Software'), ('Streaming', 'Streaming'), ('Infrastructure', 'Infrastructure'), ('Cloud', 'Cloud Services'), ('Utilities', 'Utilities'), ('Fitness', 'Fitness & Health'), ('Other', 'Other')], default='Software', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('billing_cycle', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Quarterly', 'Quarterly')], default='Monthly', max_length=20)),
                ('next_billing_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Upcoming', 'Upcoming'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_billing_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('renewal_reminder_days', models.IntegerField(default=3)),
                ('dark_mode', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
