# Generated by Django 6.1 on 2026-08-18 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_user_and_assign(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Subscription = apps.get_model('subscriptions', 'Subscription')
    UserPreferences = apps.get_model('subscriptions', 'UserPreferences')

    if not User.objects.exists():
        User.objects.create_user(
            username='demo',
            email='demo@spendr.app',
            password='demo1234',
            first_name='Demo',
            last_name='User',
        )

    demo_user = User.objects.order_by('id').first()
    if demo_user is None:
        return

    Subscription.objects.filter(owner__isnull=True).update(owner=demo_user)
    UserPreferences.objects.filter(user__isnull=True).update(user=demo_user)


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscriptions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='preferences',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(create_default_user_and_assign, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subscriptions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='preferences',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
