# Generated by Django 6.1 on 2026-08-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscription_owner_userpreferences_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
